language: node_js
before_script:
  - npm install -g grunt-cli
node_js:
   - 0.8
notifications:
    email: false
env:
    global:
      - secure: "JN2jbgXHrJN63viTp8pJidjvFvVMrwnyfvKpde3pYMs3zf2E0+cyjeTaKoJU\nrOqIQ/AmmjvYQAoQCtlc1HaPB2DFV0SKx8tiYxXWDgzMAmIlTNJftpXl2UWO\n23NBeW65+0V0WChZmBVacerX5rPVAdC48fJC2jPUoQwlgnCOQSs="
      - secure: "Aq9QMDB6t51fhShafCJczziEoTqT04C2PCE5L8kTYX/b+6E3zsEOYDCT/ozD\nlk8W0XolrRmguhAC1l8QmJvIrUifuDbOpHnGj/diX96MSA4zVOZXqkIBUlj0\ncjUyk8EqNl5f9qLje77ndIcIeYpJXGTu46AJgSYl1sndMTdT72Y="
